apiVersion: apps/v1
kind: Deployment
metadata:
  name: leak-native
  # annotations:
  #   app.openshift.io/vcs-ref: master
  #   app.openshift.io/vcs-uri: 'https://gitlab.com/ocp-demo/backend_quarkus'
  labels:
    app.kubernetes.io/component: leak-native
    app.kubernetes.io/instance: leak-native
    app.kubernetes.io/name: java
    app.kubernetes.io/part-of: leak-app
    app.openshift.io/runtime: quarkus
    app.openshift.io/runtime-version: '3.10'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leak-native
      version: v1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: leak-native
        version: v1
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: backend
        image: quay.io/voravitl/leak:native
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.1"
            memory: 50Mi
          limits:
            cpu: "0.2"
            memory: 100Mi
        env:
          - name: APP_DISHSIZE
            value: "10485760"
        ports:
        - containerPort: 8080
        securityContext:
          seccompProfile: #"RuntimeDefault" or "Localhost"
            type: RuntimeDefault
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop: ["ALL"]
          readOnlyRootFilesystem: false
      tolerations:
      - effect: NoExecute
        key: node.kubernetes.io/unreachable
        operator: Exists
        tolerationSeconds: 60
      terminationGracePeriodSeconds: 10

